name: tic-tac-toe action

on:
  push:
    branches: [ tic-tac-toe ]

jobs:
  tic_tac_toe_job:
    runs-on: ubuntu-latest
    name: Play game
    steps:
    - uses: actions/checkout@v2

    - name: Play turn
      uses: ./tic-tac-toe
      with:
        IS_AI: 'true' 

    - name: Commit and push
      run: |
        git config --global user.email "sid.palas@gmail.com"
        git config --global user.name "sid palas"
        git add ./tic-tac-toe/board.txt
        git commit -m "played turn"
        git push